services:
  client:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:covertree@mongo:27017/property-manager?authSource=admin
      - WEATHERAPI_API_KEY=b0f83a743f17419e91d170346250102
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm run seed && npm run start"

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    command: mongod --bind_ip 0.0.0.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: covertree
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet

volumes:
  mongo_data: